[2024-06-24 14:42:33,984] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: dag_with_python_dependencies_v03.get_sklearn 2023-07-26T00:00:00+00:00 [queued]>
[2024-06-24 14:42:34,062] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: dag_with_python_dependencies_v03.get_sklearn 2023-07-26T00:00:00+00:00 [queued]>
[2024-06-24 14:42:34,067] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-06-24 14:42:34,072] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2024-06-24 14:42:34,073] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-06-24 14:42:34,185] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): get_sklearn> on 2023-07-26T00:00:00+00:00
[2024-06-24 14:42:34,209] {standard_task_runner.py:52} INFO - Started process 22901 to run task
[2024-06-24 14:42:34,222] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_python_dependencies_v03', 'get_sklearn', '2023-07-26T00:00:00+00:00', '--job-id', '8853', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_dependencies.py', '--cfg-path', '/tmp/tmpn0tcz8e5', '--error-file', '/tmp/tmphcmvzxnx']
[2024-06-24 14:42:34,239] {standard_task_runner.py:77} INFO - Job 8853: Subtask get_sklearn
[2024-06-24 14:42:34,464] {logging_mixin.py:104} INFO - Running <TaskInstance: dag_with_python_dependencies_v03.get_sklearn 2023-07-26T00:00:00+00:00 [running]> on host 799b1e36e3f1
[2024-06-24 14:42:34,708] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=dag_with_python_dependencies_v03
AIRFLOW_CTX_TASK_ID=get_sklearn
AIRFLOW_CTX_EXECUTION_DATE=2023-07-26T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-26T00:00:00+00:00
[2024-06-24 14:42:48,037] {logging_mixin.py:104} INFO - sklearn with version: 0.24.2
[2024-06-24 14:42:48,091] {python.py:118} INFO - Done. Returned value was: None
[2024-06-24 14:42:48,376] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=dag_with_python_dependencies_v03, task_id=get_sklearn, execution_date=20230726T000000, start_date=20240624T144233, end_date=20240624T144248
[2024-06-24 14:42:51,540] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2024-06-24 14:42:51,612] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 22901
[2024-06-24 14:42:51,671] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-24 14:42:51,741] {base.py:273} ERROR - Exception closing connection <connection object at 0x7f82e2f738d0; dsn: 'user=airflow password=xxx dbname=airflow host=postgres', closed: 1>
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 270, in _close_connection
    self._dialect.do_close(connection)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 564, in do_close
    dbapi_connection.close()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1241, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-06-24 14:42:51,831] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-24 14:42:52,426] {process_utils.py:66} INFO - Process psutil.Process(pid=22901, status='terminated', exitcode=0, started='14:42:33') (22901) terminated with exit code 0
